import { useCallback } from "react";

export const useCadPageLayoutViewModel = (options: any) => {
  const {
    styles,
    showFeatureToggle,
    allowedFileTypes,
    i18n,
    page,
    selection,
    toolpath,
    ownership,
    fileNameDialogState,
    derived,
    controllers,
    editController,
    shortcuts,
    toast,
    handleFileCheck,
    handlePartQuantityChange,
    partUnplacedCountByPartId,
    totalUnplacedCount,
    history,
    viewport,
    isOperationHistoryEnabled,
    handleAddPlate,
    handleRemovePlate,
    remainingPartSummary,
    collaboration,
    currentUsername,
    user,
    collisionEngineRef,
    isEditFeatureEnabled,
  } = options;

  const showDrawingRibbonOnNestingDebugPage =
    typeof window !== "undefined" &&
    window.location.pathname.includes("universal-cadview-test.html");

  const handleSavePlates = useCallback(
    (newPlates: any[]) => {
      let maxY = -50;
      page.plates.forEach((plate: any) => {
        maxY = Math.max(maxY, plate.position.y + plate.height);
      });
      const adjustedPlates = newPlates.map((plate, index) => ({
        ...plate,
        position: { x: 0, y: maxY + 50 + index * (plate.height + 50) },
      }));
      page.setPlates((prev: any[]) => [...prev, ...adjustedPlates]);

      if (
        page.layoutViewMode === "single" &&
        page.selectedPlateIds.length === 0 &&
        adjustedPlates.length > 0
      ) {
        options.onPlateSelectionChange?.(adjustedPlates[0].id, [adjustedPlates[0].id]);
      }
    },
    [page.plates, page.layoutViewMode, page.selectedPlateIds.length, page.setPlates, options],
  );

  return {
    containerStyle: styles.container,
    topControlsProps: {
      showFeatureToggle,
      theme: page.theme,
      isNestingMode: page.isNestingMode,
      onToggleNestingMode: () => page.setIsNestingMode((prev: boolean) => !prev),
      allowedFileTypes,
      onFileInputChange: controllers.handleFileInput,
      handleRibbonAction: controllers.handleRibbonAction,
      setTheme: page.setTheme,
      currentLanguage: i18n.language, onLanguageChange: (lang: string) => i18n.changeLanguage(lang),
      currentShowDimensions: controllers.currentShowDimensions,
      nestingConfig: page.nestingConfig,
      setNestingConfig: page.setNestingConfig,
      toolpathSortMode: toolpath.toolpathSortMode,
      nestingProcessMenus: controllers.nestingProcessMenus,
      nestingProcessPrimaryActionDefByOperation: controllers.nestingProcessPrimaryActionDefByOperation,
      handleNestingProcessPrimaryClick: controllers.handleNestingProcessPrimaryClick,
      handleNestingProcessPinToggle: controllers.handleNestingProcessPinToggle,
      isPlatesModalOpen: page.isPlatesModalOpen,
      onClosePlatesModal: () => page.setIsPlatesModalOpen(false),
      plates: page.plates,
      onSavePlates: handleSavePlates,
      showDrawingRibbonOnNestingDebugPage,
    },
    mainContentProps: {
      styles: { mainContent: styles.mainContent, leftPanel: styles.leftPanel },
      sidePanelProps: {
        files: page.files,
        selectedFileId: page.selectedFileId,
        selectedFileIds: page.selectedListFileIds,
        checkedFileIds: page.checkedFileIds,
        onFileSelect: options.handleListFileSelect || controllers.handleFileSelect,
        onSelectionClear: options.handleListSelectionClear,
        onFileCheck: handleFileCheck,
        onFileRename: controllers.handleFileRename,
        onZoomToSelection: controllers.handleZoomToSelection,
        isNestingMode: page.isNestingMode,
        activeTab: page.activeTab,
        onTabChange: controllers.handleTabChange,
        onUpload: () => document.getElementById("file-input")?.click(),
        onPartQuantityChange: handlePartQuantityChange,
        partEntitiesByFileId: page.entitiesMap,
        partUnplacedCountByPartId,
        totalUnplacedCount,
        theme: page.theme,
        allowedFileTypes,
      },
      canvasPaneProps: {
        theme: page.theme,
        styles: { canvas: styles.canvas, button: styles.button },
        isNestingMode: page.isNestingMode,
        partActionToast: toast.partActionToast,
        toolpathPanelProps: {
          isNestingMode: page.isNestingMode,
          toolpathPlan: toolpath.toolpathPlan,
          isToolpathBusy: toolpath.isToolpathBusy,
          theme: page.theme,
          toolpathMode: toolpath.toolpathMode,
          toolpathSortMode: toolpath.toolpathSortMode,
          toolpathContourOptions: toolpath.toolpathContourOptions,
          toolpathSelectedContourId: toolpath.toolpathSelectedContourId,
          onToolpathSelectedContourIdChange: toolpath.setToolpathSelectedContourId,
          toolpathStartPointParamInput: toolpath.toolpathStartPointParamInput,
          onToolpathStartPointParamInputChange: toolpath.setToolpathStartPointParamInput,
          toolpathSequenceOrderInput: toolpath.toolpathSequenceOrderInput,
          onToolpathSequenceOrderInputChange: toolpath.setToolpathSequenceOrderInput,
          toolpathLeadInLengthInput: toolpath.toolpathLeadInLengthInput,
          onToolpathLeadInLengthInputChange: toolpath.setToolpathLeadInLengthInput,
          toolpathLeadOutLengthInput: toolpath.toolpathLeadOutLengthInput,
          onToolpathLeadOutLengthInputChange: toolpath.setToolpathLeadOutLengthInput,
          requestToolpathPlan: toolpath.requestToolpathPlan,
          requestToolpathCheck: toolpath.requestToolpathCheck,
          showToolpathOverlay: toolpath.showToolpathOverlay,
          onToggleToolpathOverlay: () => toolpath.setShowToolpathOverlay((prev: boolean) => !prev),
          applyStartPointOverride: toolpath.applyStartPointOverride,
          applyLeadOverride: toolpath.applyLeadOverride,
          applySequenceOverride: toolpath.applySequenceOverride,
          buttonStyle: styles.button,
        },
        cadViewProps: {
          entities: derived.transformedEntitiesForNesting,
          selectedFileId: page.selectedFileId,
          selectedEntityIds: selection.selectedEntityIds,
          onEntityHover: controllers.handleEntityHover,
          onEntityClick: controllers.handleEntitySelect,
          onSelectionChange: controllers.handleSelectionChange,
          contentBox: derived.visibleContentBox,
          files: page.files,
          isNestingMode: page.isNestingMode,
          isEditMode: page.isEditMode,
          editToolsEnabled: isEditFeatureEnabled,
          isScaleMode: page.isScaleMode,
          selectionBBox: controllers.selectionBBox,
          onScale: controllers.handleScale,
          hoveredEntityId: selection.hoveredEntityId,
          partsForFilling: derived.visibleParts,
          selectedPartIds: page.selectedPartIds,
          onPartSelectionChange: options.handleCadPartSelectionChange,
          layoutViewMode: page.layoutViewMode,
          remainingPartSummary,
          plates: derived.visiblePlates,
          onPartsChange: page.setNestingParts,
          collisionEngine: collisionEngineRef.current,
          enableFillRendering: derived.visibleParts.length > 0,
          onUndo: shortcuts.handleUndo,
          onRedo: shortcuts.handleRedo,
          onDelete: controllers.handleDeleteToolAction,
          onTrim: controllers.handleTrimToolAction,
          onExtend: controllers.handleExtendToolAction,
          canUndo: history.historyState?.canUndo || false,
          canRedo: history.historyState?.canRedo || false,
          onExplode: controllers.handleExplodeToolAction,
          hasEditableEntities: controllers.hasEditableGraphicEntities,
          explodeAnimationPoints: page.explodeAnimationPoints || undefined,
          onEntityCreate: controllers.handleEntityCreate,
          onEntityDragStart: controllers.handleEntityDragStart,
          onEntityDrag: controllers.handleEntityDrag,
          onEntityDragEnd: controllers.handleEntityDragEnd,
          onEntityDragCancel: controllers.handleEntityDragCancel,
          draggedEntityInfo: page.draggedEntityInfo,
          backgroundColor: page.theme === "dark" ? "#000000" : "#ffffff",
          theme: page.theme,
          partSpacing: page.nestingConfig.partSpacing,
          showDistanceGuides: page.nestingConfig.showDistanceGuides,
          distanceGuideMaxDistance: page.nestingConfig.distanceGuideMaxDistance,
          snappingEnabled: page.nestingConfig.snappingEnabled,
          snapTolerance: page.nestingConfig.snapTolerance,
          fineRotationStep: page.nestingConfig.fineRotationStep,
          onFineRotationStepChange: (val: number) =>
            page.setNestingConfig((prev: any) => ({ ...prev, fineRotationStep: val })),
          onSnappingEnabledChange: (enabled: boolean) =>
            page.setNestingConfig((prev: any) => ({ ...prev, snappingEnabled: enabled })),
          onSnapToleranceChange: (val: number) =>
            page.setNestingConfig((prev: any) => ({ ...prev, snapTolerance: val })),
          stickToEdge: page.nestingConfig.stickToEdge,
          penetrationMode: page.nestingConfig.penetrationMode,
          activeTool: editController.activeTool,
          onToolSelect: controllers.handleCadToolSelect,
          showDimensions: controllers.currentShowDimensions,
          onToggleShowDimensions: controllers.handleToggleShowDimensions,
          toolpathOverlaySegments: toolpath.toolpathOverlaySegments,
        },
        viewportValue: viewport.viewport,
        layoutEntities: derived.layout.entities,
        layoutFileLayouts: derived.layout.fileLayouts,
        inspectionResult: page.inspectionResult,
        highlightedIssueId: page.highlightedIssueId,
        showOnlyLevel: page.showOnlyLevel,
        inspectionCoordinateSpace: page.inspectionCoordinateSpace,
        handleIssueSelect: controllers.handleIssueSelect,
        handleFixAll: controllers.handleFixAll,
        isInspecting: page.isInspecting,
      },
      rightPanelsProps: {
        isNestingMode: page.isNestingMode,
        activePanel: page.activePanel,
        setActivePanel: page.setActivePanel,
        layoutsPanelWidth: page.layoutsPanelWidth,
        setLayoutsPanelWidth: page.setLayoutsPanelWidth,
        historyPanelWidth: page.historyPanelWidth,
        setHistoryPanelWidth: page.setHistoryPanelWidth,
        textPanelWidth: page.textPanelWidth,
        setTextPanelWidth: page.setTextPanelWidth,
        theme: page.theme,
        isOperationHistoryEnabled,
        plates: page.plates,
        nestingParts: page.nestingParts,
        layoutViewMode: page.layoutViewMode,
        selectedPlateIds: page.selectedPlateIds,
        onLayoutViewModeChange: options.onLayoutViewModeChange,
        onPlateSelectionChange: options.onPlateSelectionChange,
        handleAddPlate,
        handleRemovePlate,
        selectedFileId: page.selectedFileId,
        currentUserId: collaboration.myUserId || "",
        currentUsername,
        handleUndo: shortcuts.handleUndo,
        handleRedo: shortcuts.handleRedo,
        selectedTextEntity: controllers.selectedTextEntity,
        onApplyTextUpdate: controllers.handleApplyTextUpdate,
        onToast: toast.showPartActionToast,
        isAuthenticated: Boolean(user),
      },
    },
    dialogProps: {
      theme: page.theme,
      ownershipDialog: ownership.ownershipDialog,
      onOwnershipDialogKeyDownCapture: controllers.onOwnershipDialogKeyDownCapture,
      onOwnershipDialogSelectionChange: ownership.onOwnershipDialogSelectionChange,
      closeOwnershipDialog: ownership.closeOwnershipDialog,
      confirmOwnershipDialog: controllers.confirmOwnershipDialog,
      fileNameDialog: fileNameDialogState.fileNameDialog,
      onFileNameDialogKeyDownCapture: fileNameDialogState.onFileNameDialogKeyDownCapture,
      onFileNameDialogValueChange: fileNameDialogState.onFileNameDialogValueChange,
      closeFileNameDialog: fileNameDialogState.closeFileNameDialog,
      confirmFileNameDialog: fileNameDialogState.confirmFileNameDialog,
    },
  };
};
