export const getHistoryStyles = (theme: 'dark' | 'light') => ({
  container: {
    padding: '12px',
    maxHeight: '100%',
    overflowY: 'auto' as const,
    backgroundColor: theme === 'dark' ? '#1e1e1e' : '#ffffff',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    color: theme === 'dark' ? '#ffffff' : '#333333',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  title: {
    fontSize: '14px',
    fontWeight: '600' as const,
    color: theme === 'dark' ? '#e0e0e0' : '#444444',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  versionBadge: {
    fontSize: '11px',
    padding: '1px 6px',
    backgroundColor: theme === 'dark' ? '#333' : '#eee',
    borderRadius: '12px',
    color: theme === 'dark' ? '#aaa' : '#666',
    border: theme === 'dark' ? '1px solid #444' : '1px solid #ddd',
  },
  operationList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  operationItem: {
    padding: '10px 12px',
    backgroundColor: theme === 'dark' ? '#2d2d2d' : '#f8f8f8',
    borderRadius: '6px',
    borderLeft: '4px solid #4a9eff',
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
    boxShadow: theme === 'dark' ? '0 2px 4px rgba(0,0,0,0.1)' : '0 1px 3px rgba(0,0,0,0.05)',
  },
  operationItemHover: {
    backgroundColor: theme === 'dark' ? '#383838' : '#f0f0f0',
    transform: 'translateY(-1px)',
    boxShadow: theme === 'dark' ? '0 4px 8px rgba(0,0,0,0.2)' : '0 2px 5px rgba(0,0,0,0.1)',
  },
  operationMain: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  operationType: {
    fontSize: '13px',
    fontWeight: '600' as const,
    color: theme === 'dark' ? '#ffffff' : '#333333',
  },
  operationDetails: {
    fontSize: '11px',
    color: theme === 'dark' ? '#999' : '#777',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  operationMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '4px',
    paddingTop: '4px',
    borderTop: theme === 'dark' ? '1px solid #3d3d3d' : '1px solid #e5e5e5',
  },
  operationUser: {
    fontSize: '10px',
    color: theme === 'dark' ? '#777' : '#888',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  operationTime: {
    fontSize: '10px',
    color: theme === 'dark' ? '#555' : '#aaa',
  },
  userColor: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
  },
  emptyState: {
    fontSize: '13px',
    color: theme === 'dark' ? '#666' : '#999',
    textAlign: 'center' as const,
    padding: '32px 16px',
    backgroundColor: theme === 'dark' ? '#252525' : '#fdfdfd',
    borderRadius: '8px',
    border: theme === 'dark' ? '1px dashed #444' : '1px dashed #ccc',
  },
  loadingState: {
    fontSize: '13px',
    color: '#4a9eff',
    textAlign: 'center' as const,
    padding: '20px',
  },
  errorState: {
    fontSize: '13px',
    color: '#ff6b6b',
    textAlign: 'center' as const,
    padding: '20px',
  },
  buttonGroup: {
    display: 'flex',
    gap: '6px',
  },
  button: {
    flex: 1,
    padding: '6px 10px',
    backgroundColor: theme === 'dark' ? '#333' : '#ffffff',
    border: theme === 'dark' ? '1px solid #444' : '1px solid #ddd',
    borderRadius: '6px',
    color: theme === 'dark' ? '#fff' : '#333',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '500' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transition: 'all 0.2s',
  },
  buttonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
    filter: 'grayscale(1)',
  },
  select: {
    flex: 1,
    padding: '5px 8px',
    backgroundColor: theme === 'dark' ? '#2a2a2a' : '#ffffff',
    border: theme === 'dark' ? '1px solid #444' : '1px solid #ddd',
    borderRadius: '6px',
    color: theme === 'dark' ? '#bbb' : '#666',
    fontSize: '11px',
    outline: 'none',
  },
});

export type HistoryPanelStyles = ReturnType<typeof getHistoryStyles>;
