export const getStyles = (theme: "dark" | "light") => ({
  container: {
    display: "flex",
    alignItems: "stretch",
    gap: "2px",
    padding: "4px 6px",
    background:
      theme === "dark"
        ? "linear-gradient(to bottom, #2a2a2a 0%, #1a1a1a 100%)"
        : "linear-gradient(to bottom, #ffffff 0%, #f5f5f7 100%)",
    borderBottom: theme === "dark" ? "1px solid #3a3a3a" : "1px solid #d1d1d1",
    height: "90px",
    boxSizing: "border-box" as const,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial',
    color: theme === "dark" ? "#eee" : "#444",
  },
  menuGroup: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "0 4px",
    position: "relative" as const,
    height: "100%",
  },
  divider: {
    width: "1px",
    backgroundColor: theme === "dark" ? "#3a3a3a" : "#e0e0e0",
    margin: "8px 2px",
  },
  menuButton: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    backgroundColor: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "3px",
    cursor: "pointer",
    minWidth: "60px",
    height: "100%",
    transition: "all 0.1s ease-out",
    color: theme === "dark" ? "#bbb" : "#444",
  },
  menuButtonHover: {
    backgroundColor: theme === "dark" ? "#3a3a3a" : "#e1effe",
    borderColor: theme === "dark" ? "#4a4a4a" : "#b3d7ff",
    color: theme === "dark" ? "#fff" : "#000",
  },
  menuButtonActive: {
    backgroundColor: theme === "dark" ? "#4a4a4a" : "#cce5ff",
    borderColor: theme === "dark" ? "#5a5a5a" : "#99cbff",
  },
  menuIcon: {
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "6px",
  },
  menuLabel: {
    fontSize: "11px",
    fontWeight: 500,
    color: "inherit",
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  dropdown: {
    position: "absolute" as const,
    top: "calc(100% + 2px)",
    left: "0",
    minWidth: "160px",
    backgroundColor: theme === "dark" ? "#2a2a2a" : "#ffffff",
    border: theme === "dark" ? "1px solid #4a4a4a" : "1px solid #bebebe",
    borderRadius: "3px",
    boxShadow:
      theme === "dark"
        ? "0 5px 15px rgba(0,0,0,0.5)"
        : "0 5px 15px rgba(0,0,0,0.15)",
    zIndex: 1100,
    padding: "4px 0",
  },
  dropdownItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "13px",
    color: theme === "dark" ? "#eee" : "#333",
    backgroundColor: "transparent",
    border: "none",
    width: "100%",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  dropdownItemHover: {
    backgroundColor: theme === "dark" ? "#3d3d3d" : "#ecf4fc",
  },
  dropdownItemIcon: {
    width: "16px",
    height: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#555",
  },
  dropdownItemLabel: {
    flex: 1,
  },
  dropdownItemShortcut: {
    fontSize: "11px",
    color: "#888",
    marginLeft: "12px",
  },
  separator: {
    height: "1px",
    backgroundColor: theme === "dark" ? "#444" : "#e6e6e6",
    margin: "3px 10px",
  },
  submenu: {
    position: "absolute" as const,
    top: "-4px",
    left: "calc(100% - 4px)",
    minWidth: "160px",
    backgroundColor: theme === "dark" ? "#2a2a2a" : "#ffffff",
    border: theme === "dark" ? "1px solid #4a4a4a" : "1px solid #bebebe",
    borderRadius: "3px",
    boxShadow:
      theme === "dark"
        ? "0 5px 15px rgba(0,0,0,0.5)"
        : "0 5px 15px rgba(0,0,0,0.15)",
    zIndex: 1101,
    padding: "4px 0",
  },
  submenuArrow: {
    fontSize: "10px",
    marginLeft: "auto",
    color: theme === "dark" ? "#aaa" : "#888",
  },
  smallMenuButtonGroup: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
    justifyContent: "center",
    padding: "0 4px",
    gap: "4px",
  },
  smallMenuButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "8px",
    padding: "4px 8px",
    height: "36px",
    backgroundColor: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "3px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: 500,
    color: theme === "dark" ? "#eee" : "#444",
    transition: "all 0.1s ease-out",
    width: "120px",
  },
});
