export function getSidePanelStyles(theme: 'dark' | 'light') {
  return {
    container: {
      padding: '16px',
      display: 'flex',
      flexDirection: 'column' as const,
      height: '100%',
    },
    title: {
      fontSize: '16px',
      fontWeight: 'bold' as const,
      color: theme === 'dark' ? '#ffffff' : '#333333',
      marginBottom: '0',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '12px',
    },
    uploadBtn: {
      fontSize: '12px',
      padding: '4px 8px',
      backgroundColor: '#4a9eff',
      color: '#ffffff',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      transition: 'background-color 0.2s',
    },
    tabContainer: {
      display: 'flex',
      gap: '8px',
      marginBottom: '16px',
      borderBottom: theme === 'dark' ? '1px solid #3a3a3a' : '1px solid #ddd',
      paddingBottom: '12px',
    },
    tab: {
      flex: 1,
      padding: '8px 12px',
      backgroundColor: theme === 'dark' ? '#3a3a3a' : '#ffffff',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: theme === 'dark' ? '#4a4a4a' : '#ddd',
      borderRadius: '4px',
      color: theme === 'dark' ? '#ffffff' : '#333333',
      cursor: 'pointer',
      fontSize: '14px',
      textAlign: 'center' as const,
      transition: 'all 0.2s',
    },
    tabActive: {
      backgroundColor: '#4a9eff',
      borderColor: '#4a9eff',
      color: '#ffffff',
    },
    tabHover: {
      backgroundColor: theme === 'dark' ? '#4a4a4a' : '#f0f0f0',
    },
    fileItem: {
      padding: '3px 6px',
      marginBottom: '2px',
      backgroundColor: theme === 'dark' ? '#3a3a3a' : '#ffffff',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: theme === 'dark' ? 'transparent' : '#eee',
      borderRadius: '4px',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '5px',
      color: theme === 'dark' ? '#eee' : '#333',
    },
    fileItemTwoLine: {
      padding: '5px 7px',
      marginBottom: '2px',
      alignItems: 'flex-start' as const,
      gap: '6px',
    },
    fileItemSelected: {
      backgroundColor: theme === 'dark' ? '#4a9eff33' : '#e3f2fd',
      borderColor: '#4a9eff',
    },
    fileItemChecked: {
      backgroundColor: theme === 'dark' ? '#3a4a3a' : '#f1f8e9',
      borderColor: theme === 'dark' ? 'transparent' : '#c5e1a5',
    },
    checkbox: {
      width: '12px',
      height: '12px',
      cursor: 'pointer',
      accentColor: '#4a9eff',
      margin: 0,
      flexShrink: 0,
    },
    fileName: {
      flex: 1,
      minWidth: 0,
      fontSize: '12.5px',
      fontWeight: 500,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap' as const,
      lineHeight: 1.2,
    },
    fileNameInput: {
      flex: 1,
      minWidth: 0,
      fontSize: '13px',
      padding: '2px 4px',
      borderRadius: '4px',
      border: theme === 'dark' ? '1px solid #6f8fb8' : '1px solid #4a9eff',
      outline: 'none',
      backgroundColor: theme === 'dark' ? '#1d2733' : '#ffffff',
      color: theme === 'dark' ? '#ffffff' : '#333333',
    },
    nonPartRowBody: {
      flex: 1,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '2px',
    },
    fileMetaPreview: {
      fontSize: '11px',
      lineHeight: 1.2,
      color: theme === 'dark' ? '#9bb2cb' : '#5a7088',
      whiteSpace: 'nowrap' as const,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    partRowBody: {
      flex: 1,
      minWidth: 0,
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) 44px',
      gridTemplateRows: 'auto auto',
      columnGap: '8px',
      rowGap: '3px',
      alignItems: 'center',
    },
    partRowTop: {
      display: 'flex',
      alignItems: 'center',
      minWidth: 0,
      gridColumn: '1 / 2',
      gridRow: '1 / 2',
    },
    partRowBottom: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: '6px',
      minWidth: 0,
      gridColumn: '1 / 2',
      gridRow: '2 / 3',
    },
    fileNameTwoLine: {
      flex: 1,
      minWidth: 0,
      fontSize: '13.5px',
      fontWeight: 600,
      lineHeight: 1.15,
      color: theme === 'dark' ? '#e5e7eb' : '#1f2937',
      display: '-webkit-box',
      WebkitBoxOrient: 'vertical' as const,
      WebkitLineClamp: 2,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      wordBreak: 'break-word' as const,
    },
    fileNameInputTwoLine: {
      fontSize: '13.5px',
      minHeight: '26px',
      lineHeight: 1.15,
    },
    unplacedBadge: {
      fontSize: '11px',
      fontWeight: 600,
      lineHeight: 1.1,
      whiteSpace: 'nowrap' as const,
      color: theme === 'dark' ? '#facc15' : '#92400e',
      backgroundColor: theme === 'dark' ? 'rgba(250, 204, 21, 0.14)' : 'rgba(250, 204, 21, 0.2)',
      border: theme === 'dark' ? '1px solid rgba(250, 204, 21, 0.28)' : '1px solid rgba(146, 64, 14, 0.22)',
      borderRadius: '999px',
      padding: '0 5px',
    },
    thumbnailContainer: {
      width: '44px',
      height: '44px',
      minWidth: '44px',
      minHeight: '44px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gridColumn: '2 / 3',
      gridRow: '1 / 3',
      alignSelf: 'center',
    },
    thumbnailFallback: {
      fontSize: '9px',
      fontWeight: 'bold' as const,
      color: theme === 'dark' ? '#8ea2b8' : '#5a738f',
    },
    quantityControls: {
      display: 'flex',
      alignItems: 'center',
      borderRadius: '5px',
      border: theme === 'dark' ? '1px solid #4d6174' : '1px solid #c7d5e6',
      overflow: 'hidden',
      backgroundColor: theme === 'dark' ? '#132133' : '#ffffff',
    },
    quantityButton: {
      width: '20px',
      height: '20px',
      border: 'none',
      backgroundColor: theme === 'dark' ? '#1f3348' : '#edf5ff',
      color: theme === 'dark' ? '#cde4ff' : '#23517f',
      cursor: 'pointer',
      fontSize: '12px',
      lineHeight: 1,
      padding: 0,
    },
    quantityInput: {
      width: '36px',
      height: '20px',
      border: 'none',
      borderLeft: theme === 'dark' ? '1px solid #3f556c' : '1px solid #c7d5e6',
      borderRight: theme === 'dark' ? '1px solid #3f556c' : '1px solid #c7d5e6',
      textAlign: 'center' as const,
      fontSize: '11.5px',
      fontWeight: 600,
      outline: 'none',
      backgroundColor: theme === 'dark' ? '#0f1a27' : '#ffffff',
      color: theme === 'dark' ? '#e8f3ff' : '#1f3e5a',
      padding: 0,
    },
    fileCount: {
      fontSize: '12px',
      color: theme === 'dark' ? '#888' : '#666',
      marginBottom: '8px',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    selectAllBtn: {
      fontSize: '11px',
      padding: '2px 8px',
      backgroundColor: theme === 'dark' ? '#3a3a3a' : '#ffffff',
      border: theme === 'dark' ? '1px solid #5a5a5a' : '1px solid #ccc',
      borderRadius: '3px',
      color: theme === 'dark' ? '#aaa' : '#666',
      cursor: 'pointer',
    },
  };
}
