import fs from 'node:fs/promises';
import path from 'node:path';
import { parse as parseYaml } from 'yaml';

const rootDir = path.resolve(process.cwd());
const registryPath = path.join(rootDir, 'registry', 'resource-packs.yaml');
const outPath = path.join(rootDir, 'generated', 'types', 'resource-packs.ts');

type ResourcePackEntry = {
  resourcePackId: string;
  consumerAppId: string;
  description?: string;
  selectorSchema?: {
    dataDomains?: string[];
    objectTypes?: string[];
    containerIds?: string[];
  };
  actions?: string[];
};

async function main() {
  const parsed = parseYaml(await fs.readFile(registryPath, 'utf8')) as { resourcePacks?: ResourcePackEntry[] };
  const items = Array.isArray(parsed.resourcePacks) ? parsed.resourcePacks : [];

  const ids = items.map((item) => JSON.stringify(item.resourcePackId)).join(' | ') || 'string';
  const lines: string[] = [
    '// Auto-generated by contracts/scripts/generate-resource-pack-types.ts',
    '// Do not edit manually.',
    '',
    `export type ResourcePackId = ${ids};`,
    '',
    'export type ResourcePackEntry = {',
    '  resourcePackId: ResourcePackId;',
    '  consumerAppId: string;',
    '  description: string;',
    '  selectorSchema: {',
    '    dataDomains: string[];',
    '    objectTypes: string[];',
    '    containerIds: string[];',
    '  };',
    '  actions: Array<"read" | "write" | "share" | "delete">;',
    '};',
    '',
    `export const RESOURCE_PACKS: ResourcePackEntry[] = ${JSON.stringify(items, null, 2)} as ResourcePackEntry[];`,
    ''
  ];

  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, lines.join('\n'));
  console.log('[generate-resource-pack-types] generated resource packs types');
}

main().catch((error) => {
  console.error('[generate-resource-pack-types] failed:', error);
  process.exit(1);
});
