import React from 'react';
import * as Icons from './NestingRibbonIcons';
import type { NestingProcessActionDef } from './RibbonDropdowns.types';

export const MAX_PINNED_PROCESS_FAVORITES = 6;

export const NESTING_PROCESS_ACTION_DEFS: NestingProcessActionDef[] = [
    {
        id: 'check-leads-current',
        operation: 'add',
        label: '起点修正',
        enabledByDefault: true,
        groupLabel: '起点',
        icon: <Icons.StartPointIcon />,
    },
    {
        id: 'micro-edit',
        operation: 'add',
        label: '编辑微连',
        enabledByDefault: true,
        groupLabel: '微连',
        icon: <Icons.MicroJointEditIcon />,
    },
    {
        id: 'micro-auto',
        operation: 'add',
        label: '自动微连',
        enabledByDefault: true,
        groupLabel: '微连',
        icon: <Icons.MicroJointAutoIcon />,
    },
    {
        id: 'micro-batch',
        operation: 'add',
        label: '划线批量微连',
        enabledByDefault: false,
        groupLabel: '微连',
        icon: <Icons.MicroJointBatchIcon />,
    },
    {
        id: 'micro-long-edge',
        operation: 'add',
        label: '长边微连',
        enabledByDefault: false,
        groupLabel: '微连',
        icon: <Icons.MicroJointLongEdgeIcon />,
    },
    {
        id: 'cool-auto',
        operation: 'add',
        label: '自动冷却点',
        enabledByDefault: true,
        groupLabel: '冷却点',
        icon: <Icons.CoolPointIcon />,
    },
    {
        id: 'comp-apply',
        operation: 'add',
        label: '应用补偿',
        enabledByDefault: true,
        groupLabel: '补偿',
        icon: <Icons.CompensationIcon />,
    },
    {
        id: 'seal-apply',
        operation: 'add',
        label: '封口',
        enabledByDefault: true,
        groupLabel: '封口',
        icon: <Icons.SealIcon />,
    },
    {
        id: 'gap-apply',
        operation: 'add',
        label: '缺口',
        enabledByDefault: false,
        groupLabel: '封口',
        icon: <Icons.GapIcon />,
    },
    {
        id: 'overcut-apply',
        operation: 'add',
        label: '过切',
        enabledByDefault: false,
        groupLabel: '封口',
        icon: <Icons.OvercutIcon />,
    },
    {
        id: 'clear-leads',
        operation: 'delete',
        label: '清除引入引出线',
        enabledByDefault: true,
        groupLabel: '引线',
        icon: <Icons.LeadIcon />,
    },
    {
        id: 'clear-micro',
        operation: 'delete',
        label: '清除微连',
        enabledByDefault: true,
        groupLabel: '微连',
        icon: <Icons.MicroJointIcon />,
    },
    {
        id: 'delete-single-micro',
        operation: 'delete',
        label: '删除单个微连',
        enabledByDefault: false,
        groupLabel: '微连',
        icon: <Icons.DeleteIcon />,
    },
    {
        id: 'clear-cool',
        operation: 'delete',
        label: '清除冷却点',
        enabledByDefault: true,
        groupLabel: '冷却点',
        icon: <Icons.CoolPointIcon />,
    },
    {
        id: 'clear-comp',
        operation: 'delete',
        label: '取消补偿',
        enabledByDefault: true,
        groupLabel: '补偿',
        icon: <Icons.CompensationIcon />,
    },
    {
        id: 'clear-gap',
        operation: 'delete',
        label: '清除缺口/过切',
        enabledByDefault: true,
        groupLabel: '封口',
        icon: <Icons.SealIcon />,
    },
];
